# Generated by Django 3.2.8 on 2021-10-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localstatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='c_code',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='oi_code',
            field=models.CharField(default='', max_length=4),
        ),
    ]
