# Generated by Django 3.2.8 on 2021-10-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localstatus', '0003_remove_productdetail_c_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='status_code',
            field=models.CharField(default='', max_length=4),
        ),
    ]
