# Generated by Django 3.2.8 on 2021-10-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localstatus', '0004_productdetail_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='status_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
