# Generated by Django 3.2.8 on 2021-10-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oi_code', models.CharField(max_length=4)),
                ('c_code', models.CharField(max_length=4)),
                ('depart_airline', models.CharField(max_length=10)),
                ('depart_dep_airport', models.CharField(max_length=10)),
                ('depart_dest_airport', models.CharField(max_length=10)),
                ('depart_etd', models.DateTimeField()),
                ('depart_eta', models.DateTimeField()),
                ('depart_et', models.CharField(max_length=10)),
                ('depart_via', models.CharField(max_length=20)),
                ('return_airline', models.CharField(max_length=10)),
                ('return_dep_airport', models.CharField(max_length=10)),
                ('return_dest_airport', models.CharField(max_length=10)),
                ('return_etd', models.DateTimeField()),
                ('return_eta', models.DateTimeField()),
                ('return_et', models.CharField(max_length=10)),
                ('return_via', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('imgUrl', models.CharField(max_length=50)),
            ],
        ),
    ]
