# Generated by Django 3.2.8 on 2021-10-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTemp',
        ),
    ]
