# Generated by Django 3.2.8 on 2021-10-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0003_alter_flight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
