# Generated by Django 3.2.8 on 2021-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0004_alter_flight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.IntegerField(),
        ),
    ]
