# Generated by Django 3.2.8 on 2021-10-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oi_code', models.CharField(max_length=4)),
                ('c_code', models.CharField(max_length=4)),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='room', to='vp.room')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='userroom', to='vp.usertemp')),
            ],
        ),
        migrations.CreateModel(
            name='FlightReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oi_code', models.CharField(max_length=4)),
                ('c_code', models.CharField(max_length=4)),
                ('flight_id', models.ForeignKey(db_column='flight_id', on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='vp.flight')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='userflight', to='vp.usertemp')),
            ],
        ),
    ]
