# Generated by Django 3.2.8 on 2021-10-22 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0002_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightreservation',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='userflight', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='userroom', to=settings.AUTH_USER_MODEL),
        ),
    ]
